### ISSUE TITLE
Automatically delete "ms-cxh-****://" links

### ISSUE THREAD

**Issue by SoNothingMC** [ImpactDevelopment/ImpactBot#154]
soooo that link gives anyone a black screen that requires restarting the computer to get rid of. Maybe we could auto-delete them?  
(aka bring back "cruel" censorship, but used in a better way)

The protocol link: https://discord.com/channels/208753003996512258/308653317834145802/744949190731235368

**Comment by LeafHacker** [comment]
Cant see any harm in doing this, although i'm still minded to avoid automated censorship in the case of known malicious links i can see an advantage. That said if people know there is censorship going on, sometimes it leads to misplaced trust in things that don't end up censored...

**Comment by CesiumCs** [comment]
maybe just dont use windows
