### ISSUE TITLE
Support for verifying donations through bot

### ISSUE THREAD

**Issue by davisschenk** [ImpactDevelopment/ImpactBot#40]
Add a command to the bot that allows it to validate transactions and give people the donator rank in discord. Using the [PayPal Rest API](https://developer.paypal.com/docs/api/overview/#) it would be pretty easy to implement a validation of payment and a DB of donators. You could even automatically remove the rank in the event of a chargeback through the use of webhooks. Though im unsure of where Minecraft uuids for the mod are stored it is most likely possible to handle that through the bot. This would greatly improve the processing time for donations and save brady a ton of time.

**Comment by VolantTheFox** [comment]
it would not only save brady time by alleviating the issues of ppl messaging him, and him having to process information, but not having to deal with infinite 12 year olds would be a nice break i think.

**Comment by LeafHacker** [comment]
The current plan is that the server will [use paypal api](https://github.com/ImpactDevelopment/ImpactServer/commit/532c6fb6d038b03ee9a29fafd1902afd5299d298) while donating to grant a token for creating an impact account. The server can also grant donate roles etc when users join.
