### ISSUE TITLE
ImpactBot not messaging users on join

### ISSUE THREAD

**Issue by bddvlpr** [ImpactDevelopment/ImpactBot#85]
Thanks to Discord's wonderful 'intents', the bot "OnUserJoin" handlers won't be called unless it has the Members gateway intent. A way of fixing this might be to add the IntentGuildMembers intent to the main.go file. 
https://github.com/ImpactDevelopment/ImpactBot/blob/e17ce77b28e0489f7f896b0358c0bf072ca78bcf/main.go#L46

I can't test this myself as my bot in Impact has no permissions to view the verify channel.

**Comment by LeafHacker** [comment]
Thanks for the heads up
