### ISSUE TITLE
Let people remove Giveaway Ping

### ISSUE THREAD

**Issue by SoNothingMC** [ImpactDevelopment/ImpactBot#86]
**current issue:** people can’t remove the role  
**expected result:** people removing the role (using `i!giveaway` again?)

**Comment by DoctorBang** [comment]
I disagree, leave them in torture.

**Comment by Grass0001** [comment]
as someone who has the role, i also disagree

**Comment by ghost** [comment]
no.

**Comment by RandomContributor** [comment]
#95 fixes this

**Comment by SoNothingMC** [comment]
thank you for merging
